<style>
/*! CSS Used from: Embedded */
.preview_container p.MsoNormal{mso-style-qformat:yes;mso-style-parent:"";margin-top:2.0pt;margin-right:0cm;margin-bottom:2.0pt;margin-left:0cm;mso-pagination:widow-orphan;font-size:10.0pt;font-family:"Franklin Gothic Book",sans-serif;mso-ascii-font-family:"Franklin Gothic Book";mso-ascii-theme-font:minor-latin;mso-fareast-font-family:"Franklin Gothic Book";mso-fareast-theme-font:minor-latin;mso-hansi-font-family:"Franklin Gothic Book";mso-hansi-theme-font:minor-latin;mso-bidi-font-family:"Times New Roman";mso-bidi-theme-font:minor-bidi;mso-font-kerning:10.0pt;mso-ansi-language:EN-US;mso-fareast-language:EN-US;}
.preview_container h1{mso-style-priority:2;mso-style-unhide:no;mso-style-qformat:yes;mso-style-link:"Heading 1 Char";margin-top:0cm;margin-right:0cm;margin-bottom:3.0pt;margin-left:0cm;mso-add-space:auto;mso-pagination:widow-orphan;mso-outline-level:1;font-size:12.0pt;mso-bidi-font-size:16.0pt;font-family:"Franklin Gothic Medium",sans-serif;mso-ascii-font-family:"Franklin Gothic Medium";mso-ascii-theme-font:major-latin;mso-fareast-font-family:"Times New Roman";mso-fareast-theme-font:major-fareast;mso-hansi-font-family:"Franklin Gothic Medium";mso-hansi-theme-font:major-latin;mso-bidi-font-family:"Times New Roman";mso-bidi-theme-font:major-bidi;color:#006666;mso-themecolor:accent3;text-transform:uppercase;mso-font-kerning:10.0pt;mso-ansi-language:EN-US;mso-fareast-language:EN-US;mso-bidi-font-weight:normal;}
.preview_container h2{mso-style-priority:3;mso-style-qformat:yes;mso-style-link:"Heading 2 Char";margin-top:2.0pt;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;margin-bottom:.0001pt;mso-pagination:widow-orphan lines-together;page-break-after:avoid;mso-outline-level:2;font-size:10.0pt;mso-bidi-font-size:13.0pt;font-family:"Franklin Gothic Book",sans-serif;mso-ascii-font-family:"Franklin Gothic Book";mso-ascii-theme-font:minor-latin;mso-fareast-font-family:"Times New Roman";mso-fareast-theme-font:major-fareast;mso-hansi-font-family:"Franklin Gothic Book";mso-hansi-theme-font:minor-latin;mso-bidi-font-family:"Times New Roman";mso-bidi-theme-font:major-bidi;color:white;mso-themecolor:background1;text-transform:uppercase;mso-font-kerning:10.0pt;mso-ansi-language:EN-US;mso-fareast-language:EN-US;font-weight:normal;}
.preview_container p.MsoTitle{mso-style-priority:1;mso-style-unhide:no;mso-style-qformat:yes;mso-style-link:"Title Char";margin-top:20.0pt;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;mso-add-space:auto;text-align:center;mso-pagination:widow-orphan;font-size:36.0pt;mso-bidi-font-size:28.0pt;font-family:"Franklin Gothic Medium",sans-serif;mso-ascii-font-family:"Franklin Gothic Medium";mso-ascii-theme-font:major-latin;mso-fareast-font-family:"Times New Roman";mso-fareast-theme-font:major-fareast;mso-hansi-font-family:"Franklin Gothic Medium";mso-hansi-theme-font:major-latin;mso-bidi-font-family:"Times New Roman";mso-bidi-theme-font:major-bidi;color:#006666;mso-themecolor:accent3;text-transform:uppercase;mso-font-kerning:14.0pt;mso-ansi-language:EN-US;mso-fareast-language:EN-US;}
.preview_container a:link{mso-style-priority:99;color:#646464;mso-themecolor:hyperlink;text-decoration:underline;text-underline:single;}
.preview_container a:visited{mso-style-noshow:yes;mso-style-priority:99;color:#969696;mso-themecolor:followedhyperlink;text-decoration:underline;text-underline:single;}
.preview_container p.Graphic{mso-style-name:Graphic;mso-style-priority:5;mso-style-unhide:no;mso-style-qformat:yes;margin-top:2.0pt;margin-right:.7pt;margin-bottom:0cm;margin-left:0cm;margin-bottom:.0001pt;text-align:right;mso-pagination:widow-orphan;font-size:10.0pt;font-family:"Franklin Gothic Book",sans-serif;mso-ascii-font-family:"Franklin Gothic Book";mso-ascii-theme-font:minor-latin;mso-fareast-font-family:"Franklin Gothic Book";mso-fareast-theme-font:minor-latin;mso-hansi-font-family:"Franklin Gothic Book";mso-hansi-theme-font:minor-latin;mso-bidi-font-family:"Times New Roman";mso-bidi-theme-font:minor-bidi;mso-font-kerning:10.0pt;mso-ansi-language:EN-US;mso-fareast-language:EN-US;mso-no-proof:yes;}
.preview_container p.ContactInfo{mso-style-name:"Contact Info";mso-style-priority:1;mso-style-unhide:no;mso-style-qformat:yes;margin-top:2.0pt;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;margin-bottom:.0001pt;mso-pagination:widow-orphan;font-size:12.0pt;mso-bidi-font-size:10.0pt;font-family:"Franklin Gothic Book",sans-serif;mso-ascii-font-family:"Franklin Gothic Book";mso-ascii-theme-font:minor-latin;mso-fareast-font-family:"Franklin Gothic Book";mso-fareast-theme-font:minor-latin;mso-hansi-font-family:"Franklin Gothic Book";mso-hansi-theme-font:minor-latin;mso-bidi-font-family:"Times New Roman";mso-bidi-theme-font:minor-bidi;color:white;mso-themecolor:accent2;mso-font-kerning:10.0pt;mso-ansi-language:EN-US;mso-fareast-language:EN-US;font-weight:bold;mso-bidi-font-weight:normal;}
.preview_container span.SpellE{mso-style-name:"";mso-spl-e:yes;}
.preview_container span.GramE{mso-style-name:"";mso-gram-e:yes;}
.preview_container div.WordSection1{page:WordSection1;}
/*! CSS Used fontfaces */
@font-face{font-family:"Franklin Gothic Book";panose-1:2 11 5 3 2 1 2 2 2 4;mso-font-charset:0;mso-generic-font-family:swiss;mso-font-pitch:variable;mso-font-signature:647 0 0 0 159 0;}
@font-face{font-family:"Franklin Gothic Medium";panose-1:2 11 6 3 2 1 2 2 2 4;mso-font-charset:0;mso-generic-font-family:swiss;mso-font-pitch:variable;mso-font-signature:647 0 0 0 159 0;}
</style>